name: Env tests
on: push

env:
  TESTNET_SERVICE_ACCOUNT_JSON: ${{ secrets.TESTNET_SERVICE_ACCOUNT_JSON }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESTNET_SERVICE_ACCOUNT_JSON: ${{ secrets.TESTNET_SERVICE_ACCOUNT_JSON }}
    steps:
      - uses: actions/checkout@v1
      - name: Test envs
        run: |
             source ./env_test.sh
        env:
          TESTNET_SERVICE_ACCOUNT_JSON: ${{ secrets.TESTNET_SERVICE_ACCOUNT_JSON }}
